# Generated by Django 4.1.7 on 2023-03-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'verbose_name': 'Черга', 'verbose_name_plural': 'Черги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Очікувач', 'verbose_name_plural': 'Очікувачі'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User',
            new_name='qwerty',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації користувача'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(default=1, verbose_name='Порядковий номер користувача'),
        ),
    ]
