# Generated by Django 4.1.7 on 2023-03-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_alter_turn_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qwerty',
            new_name='Зареєстрований у черзі',
        ),
    ]
