# Generated by Django 4.1.7 on 2023-03-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0003_rename_qwerty_user_зареєстрований у черзі'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(default=0, verbose_name='Порядковий номер користувача'),
        ),
    ]
