# Generated by Django 4.1.7 on 2023-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0008_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='Номер телефону',
            field=models.CharField(default=390022, max_length=15),
            preserve_default=False,
        ),
    ]
