# Generated by Django 4.1.7 on 2023-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0009_remove_user_phone_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AlterField(
            model_name='user',
            name='Номер телефону',
            field=models.CharField(max_length=9),
        ),
    ]
