# Generated by Django 4.1.7 on 2023-04-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0010_remove_user_position_alter_user_номер телефону'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.user'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_text',
            field=models.TextField(null=True, verbose_name='Опис черги'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва черги'),
        ),
    ]
