# Generated by Django 4.1.7 on 2023-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0012_alter_turn_create_date_alter_turn_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='creator',
            field=models.IntegerField(verbose_name='Хазяїн'),
        ),
    ]
