# Generated by Django 4.1.7 on 2023-04-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0014_alter_user_номер телефону'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Номер телефону',
            new_name='username',
        ),
    ]
