# Generated by Django 4.1.7 on 2023-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0015_rename_номер телефону_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Зареєстрований у черзі',
            new_name='user_turn',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
