# Generated by Django 4.1.7 on 2023-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0016_rename_зареєстрований у черзі_user_user_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус черги'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='creator',
            field=models.IntegerField(verbose_name='Хазяїн черги'),
        ),
    ]
