# Generated by Django 4.1.7 on 2023-04-25 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0021_alter_user_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='expected_hours',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='expected_minutes',
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 4, 25, 17, 33, 1, 249639, tzinfo=datetime.timezone.utc)),
        ),
    ]
